Feature:

  Scenario: Task successfully created
    When I go to "/login"
    And I fill in "username1" for "username"
    And I fill in "password1" for "password"
    When I press "Se connecter"
    Given I am on "/login"
    And I should see "Vous êtes connecté en tant que username1"
    When I go to "/tasks/create"
    Then I should see "Title"
    And I should see "Content"
    And I should see "Ajouter"
    And I fill in "taskDeTest" for "task_title"
    And I fill in "La premiere task ici" for "task_content"
    When I press "Ajouter"
    Then I should be on "/tasks"
    And I should see "Superbe ! La tâche a été bien été ajoutée"

  Scenario: Task failed to created (content field is empty)
    When I go to "/login"
    And I fill in "username1" for "username"
    And I fill in "password1" for "password"
    When I press "Se connecter"
    Given I am on "/login"
    And I should see "Vous êtes connecté en tant que username1"
    When I go to "/tasks/create"
    Then I should see "Title"
    And I should see "Content"
    And I should see "Ajouter"
    And I fill in "test" for "task_title"
    And I fill in "" for "task_content"
    When I press "Ajouter"
    Then I should see "Vous devez saisir du contenu"

  Scenario: Task failed to created (title field is empty)
    When I go to "/login"
    And I fill in "username1" for "username"
    And I fill in "password1" for "password"
    When I press "Se connecter"
    Given I am on "/login"
    And I should see "Vous êtes connecté en tant que username1"
    When I go to "/tasks/create"
    Then I should see "Title"
    And I should see "Content"
    And I should see "Ajouter"
    And I fill in "" for "task_title"
    And I fill in "test task" for "task_content"
    When I press "Ajouter"
    Then I should see "Vous devez saisir un titre"


