name: Continious Integration

on: push

jobs:
  quality:
    name: Quality checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '7.4'
#          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
      - name: Install dependencies
        run: composer install
      - name: Update dependencies
        run: composer update --prefer-dist --no-progress
      - name: Create db
        run: php bin/console doctrine:database:create --env=test
      - name: Migrate database
        run: php bin/console doctrine:schema:update --force --env=test
      - name: Data fixtures
        run: php bin/console doctrine:fixtures:load --no-interaction --env=test
      - name: PHP Unit tests
        if: ${{ always() }}
        run: php ./vendor/bin/phpunit
      - name: Functionnal testing (behat)
        run: php vendor/bin/behat
        #- name: doctrine
        # if: ${{ always() }}
        #run: php bin/console doctrine:database:create --env=test
      # - run: symfony console doctrine:database:create --env=test
      #- run: symfony console doctrine:migrations:migrate --force --env=test
      #- run: symfony console doctrine:fixtures:load --force --env=test
      #- run: symfony run bin/phpunit
      #- run: echo "test complete"
